name: Determine New Version Sub-Workflow

on:
  workflow_call:
    inputs:
      application:
        required: true
        type: string
      version_type:
        required: true
        type: string

jobs:
  calculate-version:
    name: Calculate Version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch all tags
        run: git fetch --tags

      - name: Determine New Version
        id: determine_version
        run: |
          APPLICATION=${{ inputs.application }}
          VERSION_TYPE=${{ inputs.version_type }}

          # Fetch the latest tag for the application
          LATEST_TAG=$(git tag --list "${APPLICATION}:*" --sort=-v:refname | head -n 1 | cut -d':' -f2)
          LATEST_TAG=${LATEST_TAG:-"0.0.0"}

          echo "Latest tag for ${APPLICATION}: ${LATEST_TAG}"

          # Parse the latest version
          IFS='.' read -r MAJOR MINOR PATCH <<< "$LATEST_TAG"

          # Increment the version based on the version type
          case $VERSION_TYPE in
            major)
              MAJOR=$((MAJOR + 1))
              MINOR=0
              PATCH=0
              ;;
            minor)
              MINOR=$((MINOR + 1))
              PATCH=0
              ;;
            patch)
              PATCH=$((PATCH + 1))
              ;;
          esac

          NEW_VERSION="$MAJOR.$MINOR.$PATCH"
          echo "new_version=$NEW_VERSION" >> $GITHUB_ENV
          echo "New version for ${APPLICATION}: $NEW_VERSION"

      - name: Output New Version
        run: |
          echo "New Version: ${{ env.new_version }}"
