name: Get Version Label Subworkflow

on:
  workflow_call:
    inputs:
      application:
        required: true
        type: string
      pr_number:
        required: true
        type: string
    secrets:
      GH_TOKEN:
        required: true

    outputs:
      version_type:
        description: The version type (patch, minor, or major) for the application
        value: ${{ jobs.find-version-label.outputs.version_type }}

jobs:
  find-version-label:
    name: Find Version Label
    runs-on: ubuntu-latest

    outputs:
      version_type: ${{ steps.determine_label.outputs.version_type }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get PR Labels
        id: get_labels
        run: |
          PR_NUMBER=${{ inputs.pr_number }}
          LABELS=$(gh pr view $PR_NUMBER --json labels --jq '.labels[].name')
          echo "Labels: $LABELS"
          echo "labels=$LABELS" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Determine Version Label
        id: determine_label
        run: |
          APPLICATION="${{ inputs.application }}"
          LABELS="${LABELS}"

          # Define valid labels for the application
          VALID_LABELS=("${APPLICATION}:patch" "${APPLICATION}:minor" "${APPLICATION}:major")

          VERSION_TYPE=""

          # Loop over each label (split by spaces if multiple labels are present)
          for LABEL in $LABELS; do
            if [[ " ${VALID_LABELS[@]} " =~ " $LABEL " ]]; then
              VERSION_TYPE=$(echo $LABEL | cut -d':' -f2)
              break
            fi
          done

          echo "version_type=${VERSION_TYPE}" >> $GITHUB_OUTPUT

