name: Get Version Label Subworkflow

on:
  workflow_call:
    inputs:
      application:
        required: true
        type: string
      pr_number:
        required: true
        type: string
    secrets:
      GH_TOKEN:
        required: true

    outputs:
      version_type:
        description: The version type (patch, minor, or major) for the application
        value: ${{ jobs.find-version-label.outputs.version_type }}

jobs:
  find-version-label:
    name: Find Version Label
    runs-on: ubuntu-latest
    outputs:
      version_type: ${{ steps.determine_label.outputs.version_type }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get PR Labels
        id: get_labels
        run: |
          PR_NUMBER=${{ inputs.pr_number }}
          LABELS=$(gh pr view $PR_NUMBER --json labels --jq '.labels[].name')
          echo "$LABELS" > labels.txt
          echo "Labels:"
          cat labels.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Determine Version Label
        id: determine_label
        run: |
          APPLICATION="${{ inputs.application }}"
          VALID_LABELS=("${APPLICATION}:patch" "${APPLICATION}:minor" "${APPLICATION}:major")

          VERSION_TYPE=""
          VALID_COUNT=0

          # Read and process labels
          while IFS= read -r LABEL; do
            if [[ " ${VALID_LABELS[@]} " =~ " $LABEL " ]]; then
              VERSION_TYPE=$(echo "$LABEL" | cut -d':' -f2)
              VALID_COUNT++
            fi
          done < labels.txt

          # Fail if more than one valid label is found
          if [[ $VALID_COUNT -gt 1 ]]; then
            echo "::error::More than one valid label found for application '${APPLICATION}'."
            exit 1
          fi

          # Output the version type
          echo "version_type=${VERSION_TYPE}" >> $GITHUB_OUTPUT


