name: "deploy"
on:
  workflow_call:
    inputs:
      application:
        required: true
        type: string
      version:
        required: true
        type: string
        description: format MAJOR.MINOR.PATCH
      manual_deploy:
        required: false
        type: boolean
        default: false

concurrency: ${{ inputs.application }}
jobs:
  deploy-qa:
    runs-on: ubuntu-latest
    environment:
      name: QA
    steps:
      - name: deploy
        run: echo 'deploying "${{ inputs.application }}" version "${{ inputs.version }}" to QA'
  gatekeep-staging:
    if: ${{ inputs.manual_deploy == 'true' }}
    runs-on: ubuntu-latest
    environment:
      name: gatekeep-staging
    steps:
      - name: gatekeep
        run: echo "awaiting approval"
  deploy-staging:
    needs: [deploy-qa, gatekeep-staging]
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        run: echo 'deploying "${{ inputs.application }}" version "${{ inputs.version }}" to staging'
  gatekeep-production:
    if: ${{ inputs.manual_deploy == 'true' }}
    runs-on: ubuntu-latest
    environment:
      name: gatekeep-production
    steps:
      - name: gatekeep
        run: echo "awaiting approval
  deploy-production:
    runs-on: ubuntu-latest
    needs: [deploy-staging, gatekeep-production]
    steps:
      - name: deploy
        run: echo 'deploying "${{ inputs.application }}" version "${{ inputs.version }}" to production'
