name: ephemeral-build-pro

on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - reopened
      - ready_for_review

jobs:
  get-pro-version-label:
    name: Get Pro Version Label
    uses: ./.github/workflows/_get_version_label.yml
    with:
      application: pro
      pr_number: ${{ github.event.pull_request.number }}
    secrets:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  calculate-pro-new-version:
    name: Calculate Pro New Version
    needs: get-pro-version-label
    uses: ./.github/workflows/_version_bump.yml
    with:
      application: pro
      version_type: ${{ needs.get-pro-version-label.outputs.version_type }}

  spin-up-pro-environment:
    name: Spin Up Pro Ephemeral Environment
    needs: calculate-pro-new-version
    runs-on: ubuntu-latest

    steps:
      - name: Docker Build for Pro
        run: |
          echo "Building Docker image for Pro with version: ${{ needs.calculate-pro-new-version.outputs.new_version }}"
          # Placeholder for Docker build command
          echo "docker build -t pro-app:${{ needs.calculate-pro-new-version.outputs.new_version }} ."
