name: main-branch-workflow
on:
  push:
    branches:
      - main

permissions: write-all

jobs:
  get-pro-version-label:
    name: Get Pro Version Label
    uses: ./.github/workflows/_get_version_label.yml
    with:
      application: pro
      pr_number: ${{ github.event.pull_request.number }}
    secrets:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  calculate-pro-new-version:
    name: Calculate Pro New Version
    if: ${{ needs.get-pro-version-label.outputs.version_type }}
    needs: get-pro-version-label
    uses: ./.github/workflows/_determine_new_version.yml
    with:
      application: pro
      version_type: ${{ needs.get-pro-version-label.outputs.version_type }}

  tag-pro-version:
    name: Apply Pro Tag
    needs: calculate-pro-new-version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Apply new tags
        run: |
          git tag "pro-${{ needs.calculate-pro-new-version.outputs.new_version }}"
          echo "Tagged pro with version ${{ needs.calculate-pro-new-version.outputs.new_version }}"
          git push --tags

  get-investor-version-label:
    name: Get Investor Version Label
    uses: ./.github/workflows/_get_version_label.yml
    with:
      application: investor
      pr_number: ${{ github.event.pull_request.number }}
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  calculate-investor-new-version:
    name: Calculate Investor New Version
    if: ${{ needs.get-investor-version-label.outputs.version_type }}
    needs: get-investor-version-label
    uses: ./.github/workflows/_determine_new_version.yml
    with:
      application: investor
      version_type: ${{ needs.get-investor-version-label.outputs.version_type }}

  tag-investor-version:
    name: Apply Investor Tag
    needs: calculate-investor-new-version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Apply new tags
        run: |
          git tag "investor-${{ needs.calculate-investor-new-version.outputs.new_version }}"
          echo "Tagged investor with version ${{ needs.calculate-investor-new-version.outputs.new_version }}"
          git push --tags

  check-if-manual-deploy:
    name: Get Manual Deploy Label
    runs-on: ubuntu-latest
    outputs:
      manual_deploy: ${{ steps.get_manual_deploy_label.outputs.manual_deploy }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get PR Labels
        id: get_labels
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          LABELS=$(gh pr view $PR_NUMBER --json labels --jq '.labels[].name')
          echo "labels=$LABELS" >> $GITHUB_ENV

      - name: Extract Manual Deploy Label
        id: get_manual_deploy_label
        env:
          LABELS: ${{ env.labels }}
        run: |
          if echo "$LABELS" | grep -q "manual deploy"; then
            echo "manual_deploy=true" >> $GITHUB_OUTPUT
          else
            echo "manual_deploy=false" >> $GITHUB_OUTPUT
          fi

  deploy_pro:
    name: Deploy Pro Application
    needs: [tag-pro-version, check-if-manual-deploy]
    uses: ./.github/workflows/deploy.yml
    with:
      application: pro
      version: ${{ needs.outputs.pro_new_version }}
      manual_deploy: ${{ needs.check-if-manual-deploy.outputs.manual_deploy }}

  deploy_investor:
    name: Deploy Investor Application
    needs: [tag-investor-version, check-if-manual-deploy]
    uses: ./.github/workflows/deploy.yml
    with:
      application: investor
      version: ${{ needs.outputs.investor_new_version }}
      manual_deploy: ${{ needs.check-if-manual-deploy.outputs.manual_deploy }}
