name: main-branch-workflow
on:
  push:
    branches:
      - main

permissions: write-all

jobs:
  calculate-and-tag-new-version:
    name: Calculate and Apply Tags
    runs-on: ubuntu-latest
    outputs:
      pro_new_version: ${{ steps.determine_pro_version.outputs.new_version }}
      investor_new_version: ${{ steps.determine_investor_version.outputs.new_version }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch all tags
        run: git fetch --tags

      - name: Get Pro Version Label
        id: get_pro_version_label
        uses: ./.github/workflows/_get_version_label.yml
        with:
          application: pro
          pr_number: ${{ github.event.pull_request.number }}

      - name: Get Investor Version Label
        id: get_investor_version_label
        uses: ./.github/workflows/_get_version_label.yml
        with:
          application: investor
          pr_number: ${{ github.event.pull_request.number }}

      - name: Determine Pro Version
        id: determine_pro_version
        uses: ./.github/workflows/_determine_new_version.yml
        with:
          application: pro
          version_type: ${{ steps.get_pro_version_label.outputs.version_type }}

      - name: Determine Investor Version
        id: determine_investor_version
        uses: ./.github/workflows/_determine_new_version.yml
        with:
          application: investor
          version_type: ${{ steps.get_investor_version_label.outputs.version_type }}

      - name: Apply new tags
        run: |
          if [[ -n "${{ steps.determine_pro_version.outputs.new_version }}" ]]; then
            git tag "pro-${{ steps.determine_pro_version.outputs.new_version }}"
            echo "Tagged pro with version ${{ steps.determine_pro_version.outputs.new_version }}"
          fi
          if [[ -n "${{ steps.determine_investor_version.outputs.new_version }}" ]]; then
            git tag "investor-${{ steps.determine_investor_version.outputs.new_version }}"
            echo "Tagged investor with version ${{ steps.determine_investor_version.outputs.new_version }}"
          fi

          # Push tags back to the repository
          git push --tags

  check-if-manual-deploy:
    name: Get Manual Deploy Label
    needs: [calculate-and-tag-new-version]
    runs-on: ubuntu-latest
    outputs:
      manual_deploy: ${{ steps.get_manual_deploy_label.outputs.manual_deploy }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get PR Labels
        id: get_labels
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          LABELS=$(gh pr view $PR_NUMBER --json labels --jq '.labels[].name')
          echo "$LABELS" > labels.txt
          echo "Labels:"
          cat labels.txt

      - name: Get Manual Deploy Label
        id: get_manual_deploy_label
        run: |
          echo "manual_deploy=contains(env.labels, 'manual deploy')" >> $GITHUB_ENV

  deploy_pro:
    name: Deploy Pro Application
    needs: [calculate-and-tag-new-version, check-if-manual-deploy]
    uses: ./.github/workflows/deploy.yml
    if: ${{ needs.calculate-and-tag-new-version.outputs.pro_new_version }}
    with:
      application: pro
      version: ${{ needs.outputs.pro_new_version }}
      manual_deploy: ${{ needs.check-if-manual-deploy.outputs.manual_deploy }}

  deploy_investor:
    name: Deploy Investor Application
    needs: [calculate-and-tag-new-version, check-if-manual-deploy]
    uses: ./.github/workflows/deploy.yml
    if: ${{ needs.calculate-and-tag-new-version.outputs.investor_new_version }}
    with:
      application: investor
      version: ${{ needs.outputs.investor_new_version }}
      manual_deploy: ${{ needs.check-if-manual-deploy.outputs.manual_deploy }}
